### ISSUE TITLE
Addon being added to the Export menu options instead of Import options

### ISSUE THREAD

**Issue by pweyyc** [stante/blendm3#12]
Lines 1055 and 1059 are placing and removing the menu option in/from the wrong menu area. It should be managed in IMPORT not EXPORT.

```
1055 bpy.types.TOPBAR_MT_file_export.append(menu_func)
1059 bpy.types.TOPBAR_MT_file_export.remove(menu_func)
```
change TOPBAR_MT_file_**export** to TOPBAR_MT_file_**import**

**Comment by stante** [comment]
Thanks for pointing that out. Commit a12c736c89111c4247fbb0bae6f6892514015d3a fixes that issue.
